blank_issues_enabled: false
contact_links:
  - name: ✏ Documentation improvement
    about: Please open the PR instead!
    url: https://github.com/Meqn/pipflow/pulls
  - name: ✨ Feature Request / idea
    url: https://github.com/Meqn/pipflow/discussions/new
    about: Missing something in MobX? Let us know.
  - name: 💬 Question / Discussion
    about: Feel free to ask anything.
    url: https://github.com/Meqn/pipflow/discussions/new
  - name: 📖 View documentation
    url: https://pipflow.mengqing.org
    about: Official pipflow documentation.